apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
  description: My sample application
  annotations:
    github.com/project-slug: devthink1/backstage
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
